<!-- Plugins css-->
<link href="<?php echo base_url(); ?>public/assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/assets/plugins/switchery/css/switchery.min.css" rel="stylesheet" />
<link href="<?php echo base_url(); ?>public/assets/plugins/multiselect/css/multi-select.css"  rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
<link href="<?php echo base_url(); ?>public/assets/plugins/bootstrap-sweetalert/sweet-alert.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>public/assets/plugins/jstree/style.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/css/core.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/css/components.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/css/icons.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/css/pages.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url(); ?>public/assets/css/responsive.css" rel="stylesheet" type="text/css" />

<!-- DataTables -->
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/buttons.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/fixedHeader.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/scroller.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.colVis.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo base_url(); ?>public/assets/plugins/datatables/fixedColumns.dataTables.min.css" rel="stylesheet" type="text/css"/>

