    <link href="<?php echo base_url(); ?>public/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo base_url(); ?>public/assets/css/core.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo base_url(); ?>public/assets/css/components.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo base_url(); ?>public/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo base_url(); ?>public/assets/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo base_url(); ?>public/assets/css/responsive.css" rel="stylesheet" type="text/css" />