
<script src="<?php echo base_url(); ?>public/assets/js/modernizr.min.js"></script>
<!-- jQuery  -->
<script src="<?php echo base_url(); ?>public/assets/js/jquery.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/bootstrap.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/detect.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/fastclick.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.slimscroll.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.blockUI.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/waves.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/wow.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.nicescroll.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.scrollTo.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/switchery/js/switchery.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/multiselect/js/jquery.multi-select.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/jquery-quicksearch/jquery.quicksearch.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/select2/js/select2.min.js" type="text/javascript"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-select/js/bootstrap-select.min.js" ></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js" ></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/jstree/jstree.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/pages/jquery.tree.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js"></script> 
<script src="<?php echo base_url(); ?>public/assets/plugins/moment/moment.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/timepicker/bootstrap-timepicker.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/clockpicker/js/bootstrap-clockpicker.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?php echo base_url(); ?>public/assets/pages/jquery.form-advanced.init.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.core.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.app.js"></script>
 
<script src="<?php echo base_url(); ?>public/assets/plugins/bootstrap-sweetalert/sweet-alert.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/pages/jquery.sweet-alert.init.js"></script>
<script src="<?php echo base_url(); ?>public/assets/pages/jquery.form-pickers.init.js"></script>
<!-- jQuery Datatables -->
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/buttons.bootstrap.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/jszip.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/pdfmake.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/vfs_fonts.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/buttons.print.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.fixedHeader.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/responsive.bootstrap.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.scroller.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.colVis.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/datatables/dataTables.fixedColumns.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/pages/datatables.init.js"></script>
<script src="<?php echo base_url(); ?>public/assets/plugins/parsleyjs/parsley.min.js"></script>

 

<script type="text/javascript">
	$(document).ready(function() {
		$('form').parsley();
	});
</script>
