<script src="<?php echo base_url(); ?>public/assets/js/modernizr.min.js"></script>
<!-- jQuery  -->
<script src="<?php echo base_url(); ?>public/assets/js/jquery.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/bootstrap.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/detect.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/fastclick.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.slimscroll.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.blockUI.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/waves.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/wow.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.nicescroll.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.scrollTo.min.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.core.js"></script>
<script src="<?php echo base_url(); ?>public/assets/js/jquery.app.js"></script>